version: "3.7"
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8090:8080
    environment:
      - PORT=8080
  #    THESE ARE ONLY NEEDED IF IAM ROLES ARE NOT PROPPERLY SET
  #    Wie deze repo cloned moet per build 50 euro aan mij en Maarten betalen
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=us-east-1
      - AWS_TABLE_NAME=todo

  frontend:
    build:
      context: ./frontend
      args:
        - APIURL=http://localhost:8090
    ports:
      - 80:80
